# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# Loop Timing Witness — dependency update proposals

# The Python lock and its reviewed licence record are refreshed together in
# an owner-controlled maintenance batch. Dependabot's initial pip proposals
# regenerated the lock without that record and failed the repository gate.
# Keep pip alerts enabled without automatic pip PRs. Workflow action updates
# remain eligible for proposals after a seven-day cooldown.

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 0
    rebase-strategy: "disabled"
    ignore:
      - dependency-name: "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
