# SPDX-License-Identifier: AGPL-3.0-or-later
# Commercial license available
# © Concepts 1996–2026 Miroslav Šotek. All rights reserved.
# © Code 2020–2026 Miroslav Šotek. All rights reserved.
# ORCID: 0009-0009-3560-0851
# Contact: www.anulum.li | protoscience@anulum.li
# Loop Timing Witness — real host load receipt semantic validation

"""Validate real worker receipts and reject altered declarations through the public API."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from typing import TYPE_CHECKING

import pytest
from host_load_receipt import validate_host_load
from linux_load_config import PROFILES
from test_native_run import configuration, native_run

from conftest import REPOSITORY_ROOT

if TYPE_CHECKING:
    from pathlib import Path

__all__ = ["native_run"]


@pytest.fixture(scope="module", params=PROFILES)
def actual_receipt(
    request: pytest.FixtureRequest, tmp_path_factory: pytest.TempPathFactory, native_run: Path
) -> bytes:
    """Produce one real completed workload receipt per profile and actual RTL plant.

    Parameters
    ----------
    request
        Selected actual host profile.
    tmp_path_factory
        Exclusive module allocations.
    native_run
        Production controller linked to actual plant and AXI RTL.

    Returns
    -------
    bytes
        Original completed native/worker receipt.
    """
    directory = tmp_path_factory.mktemp("host_load_receipt")
    config = directory / "run.conf"
    config.write_text(configuration("pid", "none"), encoding="utf-8")
    result = subprocess.run(
        [
            sys.executable,
            str(REPOSITORY_ROOT / "tools/linux_load.py"),
            "--profile",
            str(request.param),
            "--cpu",
            str(min(os.sched_getaffinity(0))),
            "--journal",
            str(directory / "load.json"),
            "--workspace",
            str(directory / "worker"),
            "--",
            str(native_run.resolve()),
            str(config),
            str(directory / "events.bin"),
            str(directory / "raw.csv"),
        ],
        capture_output=True,
        text=True,
        check=False,
        timeout=30,
    )
    assert result.returncode == 0, result.stdout + result.stderr
    return (directory / "load.json").read_bytes()


def test_completed_receipt(actual_receipt: bytes) -> None:
    """Accept exact operation totals and time brackets generated by the actual worker.

    Parameters
    ----------
    actual_receipt
        Original complete receipt from native execution with host load.
    """
    assert validate_host_load(actual_receipt) == json.loads(actual_receipt)


@pytest.mark.parametrize(
    "mutation",
    [
        "schema",
        "cpu",
        "pid",
        "start",
        "end",
        "duration",
        "network",
        "storage",
        "counter",
        "zero_chunks",
        "scheduler",
        "priority",
        "affinity",
        "nice",
        "checksum",
    ],
)
def test_altered_receipt(actual_receipt: bytes, mutation: str) -> None:
    """Reject contradictory fields in a real receipt without fabricating a run.

    Parameters
    ----------
    actual_receipt
        Original complete actual worker receipt.
    mutation
        One schema, resource, scheduling, time or count contradiction.
    """
    receipt = json.loads(actual_receipt)
    policy, counters = receipt["policy"], receipt["counters"]
    changes = {
        "schema": (receipt, "schema", "unknown"),
        "cpu": (receipt, "requested_cpu", receipt["requested_cpu"] + 1),
        "pid": (receipt, "native_pid", receipt["worker_pid"]),
        "start": (receipt, "started_ns", receipt["native_started_ns"] + 1),
        "end": (receipt, "finished_ns", receipt["native_finished_ns"] - 1),
        "duration": (receipt, "native_finished_ns", receipt["native_started_ns"]),
        "network": (
            receipt,
            "network_scope",
            None if receipt["profile"] == "network" else "loopback_udp",
        ),
        "storage": (
            receipt,
            "storage_scope",
            None if receipt["profile"] == "storage" else "owned_file_fsync",
        ),
        "counter": (counters, "chunks", counters["chunks"] + 1),
        "zero_chunks": (counters, "chunks", 0),
        "scheduler": (policy, "scheduler", 1),
        "priority": (policy, "priority", 1),
        "affinity": (
            policy,
            "affinity_cpus",
            [receipt["requested_cpu"], receipt["requested_cpu"] + 1],
        ),
        "nice": (policy, "nice", 20),
        "checksum": (receipt, "checksum", -1),
    }
    target, key, value = changes[mutation]
    target[key] = value
    with pytest.raises(ValueError, match="host load"):
        validate_host_load(json.dumps(receipt).encode())


def test_truncated_receipt(actual_receipt: bytes) -> None:
    """Refuse truncated original worker JSON through the public receipt reader.

    Parameters
    ----------
    actual_receipt
        Original complete actual worker receipt.
    """
    with pytest.raises(ValueError, match="host load receipt"):
        validate_host_load(actual_receipt.rstrip()[:-1])


@pytest.mark.parametrize("actual_receipt", ["network"], indirect=True)
def test_udp_resource_limit(actual_receipt: bytes) -> None:
    """Refuse oversized datagrams declared by an actual network receipt.

    Parameters
    ----------
    actual_receipt
        Completed original actual worker receipt.
    """
    receipt = json.loads(actual_receipt)
    receipt["working_set_bytes"] = 60001
    with pytest.raises(ValueError, match="host load policy, scope"):
        validate_host_load(json.dumps(receipt).encode())
